version: "3.8"
services:
  dev:
    build: .
    image: minesweeper-ebiten-dev:latest
    container_name: minesweeper-ebiten
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"   # for WASM dev server
    command: sleep infinity
